resolver 223.5.5.5 8.8.8.8 8.8.4.4 valid=31536000s;

server {
    listen 80;
    client_max_body_size 500M;

    # set $backend "http://192.168.1.14:11002"; # 玉喜
    # set $backend "http://192.168.1.30:11002"; # 少奇
    # set $backend "https://k8spreapi.enableai.cn"; # 预览环境
    # set $backend "https://app.enableai.cn"; # 线上环境
    # set $backend "https://k8stestapi1.enableai.cn"; # stage环境-1
    # set $backend "https://k8stestapi2.enableai.cn"; # stage环境-2
    set $backend "https://k8sdevtestapi1.enableai.cn"; # 开发环境-1
    # set $backend "https://k8sdevtestapi2.enableai.cn"; # 开发环境-2

    location /core {
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
    }

    location /socket.io {
        proxy_pass $backend;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
    }

    location /audio-proxy {
        proxy_pass http://host.docker.internal:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /2d-proxy {
        proxy_pass http://host.docker.internal:3004;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /data-proxy {
        proxy_pass http://host.docker.internal:3003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /text-proxy {
        proxy_pass http://host.docker.internal:3002;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /text-v2-proxy {
        proxy_pass http://host.docker.internal:3006;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /tools {
        proxy_pass http://host.docker.internal:3200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location / {
        proxy_pass http://host.docker.internal:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
